name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  validate:
  
    runs-on: "ubuntu-latest"
    name: Validate

    steps:
        - uses: "actions/checkout@v3"
        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"
            ignore: brands
        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"